// ─── NolTech Arbitrage Scanner — Component Seed Data ─────────────────────────
// eBay sold price ranges based on 2024–2025 completed listings.
// Each entry: { id, category, name, valueLow, valueMid, valueHigh, demand, notes }
// demand: 'high' | 'medium' | 'low'
// category: screen | ram | ssd | hdd | cpu_mobile | cpu_desktop | gpu | battery | charger | keyboard | motherboard | other

export const COMPONENT_SEED = [
  // ─── SCREENS ──────────────────────────────────────────────────────────────
  {
    id: 'seed-001',
    category: 'screen',
    name: '13.3" FHD IPS Display Assembly (laptop)',
    valueLow: 22,
    valueMid: 38,
    valueHigh: 55,
    demand: 'high',
    notes: 'Common size across Dell/Lenovo/HP ultrabooks',
  },
  {
    id: 'seed-002',
    category: 'screen',
    name: '14" FHD IPS Display Assembly (laptop)',
    valueLow: 28,
    valueMid: 44,
    valueHigh: 65,
    demand: 'high',
    notes: 'ThinkPad T/E series, Dell Latitude, HP EliteBook',
  },
  {
    id: 'seed-003',
    category: 'screen',
    name: '15.6" FHD IPS Display Assembly (laptop)',
    valueLow: 30,
    valueMid: 48,
    valueHigh: 70,
    demand: 'high',
    notes: 'Most common laptop screen size',
  },
  {
    id: 'seed-004',
    category: 'screen',
    name: '15.6" FHD TN Display Assembly (laptop)',
    valueLow: 18,
    valueMid: 28,
    valueHigh: 42,
    demand: 'medium',
    notes: 'TN panels — lower value than IPS',
  },
  {
    id: 'seed-005',
    category: 'screen',
    name: '13.3" 2560x1600 Display (MacBook Pro)',
    valueLow: 65,
    valueMid: 110,
    valueHigh: 160,
    demand: 'medium',
    notes: 'MacBook Pro retina — model-specific',
  },
  {
    id: 'seed-006',
    category: 'screen',
    name: '15.4" Retina Display (MacBook Pro)',
    valueLow: 80,
    valueMid: 130,
    valueHigh: 200,
    demand: 'medium',
    notes: 'MacBook Pro 15 — high value but model-specific',
  },

  // ─── RAM ──────────────────────────────────────────────────────────────────
  {
    id: 'seed-007',
    category: 'ram',
    name: 'DDR3 4GB SO-DIMM (laptop)',
    valueLow: 4,
    valueMid: 8,
    valueHigh: 13,
    demand: 'low',
    notes: 'DDR3 demand declining; bulk lots only',
  },
  {
    id: 'seed-008',
    category: 'ram',
    name: 'DDR3 8GB SO-DIMM (laptop)',
    valueLow: 7,
    valueMid: 12,
    valueHigh: 18,
    demand: 'low',
    notes: 'Still used in older ThinkPads/Latitudes',
  },
  {
    id: 'seed-009',
    category: 'ram',
    name: 'DDR4 4GB SO-DIMM (laptop)',
    valueLow: 6,
    valueMid: 11,
    valueHigh: 17,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-010',
    category: 'ram',
    name: 'DDR4 8GB SO-DIMM (laptop)',
    valueLow: 10,
    valueMid: 18,
    valueHigh: 26,
    demand: 'high',
    notes: 'Most common laptop upgrade — consistent demand',
  },
  {
    id: 'seed-011',
    category: 'ram',
    name: 'DDR4 16GB SO-DIMM (laptop)',
    valueLow: 20,
    valueMid: 34,
    valueHigh: 50,
    demand: 'high',
    notes: 'Strong demand for upgrades',
  },
  {
    id: 'seed-012',
    category: 'ram',
    name: 'DDR4 32GB SO-DIMM (laptop)',
    valueLow: 38,
    valueMid: 60,
    valueHigh: 85,
    demand: 'medium',
    notes: 'Niche but good margin',
  },
  {
    id: 'seed-013',
    category: 'ram',
    name: 'DDR5 16GB SO-DIMM (laptop)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'medium',
    notes: 'Newer — growing demand',
  },
  {
    id: 'seed-014',
    category: 'ram',
    name: 'DDR4 8GB DIMM (desktop)',
    valueLow: 8,
    valueMid: 15,
    valueHigh: 22,
    demand: 'high',
    notes: 'Desktop RAM — fast sell',
  },
  {
    id: 'seed-015',
    category: 'ram',
    name: 'DDR4 16GB DIMM (desktop)',
    valueLow: 15,
    valueMid: 26,
    valueHigh: 38,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-016',
    category: 'ram',
    name: 'DDR4 32GB DIMM (desktop)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'medium',
    notes: '',
  },

  // ─── SSDs ─────────────────────────────────────────────────────────────────
  {
    id: 'seed-017',
    category: 'ssd',
    name: '2.5" SATA SSD 128GB',
    valueLow: 7,
    valueMid: 12,
    valueHigh: 18,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-018',
    category: 'ssd',
    name: '2.5" SATA SSD 256GB',
    valueLow: 10,
    valueMid: 18,
    valueHigh: 28,
    demand: 'high',
    notes: 'Bread and butter',
  },
  {
    id: 'seed-019',
    category: 'ssd',
    name: '2.5" SATA SSD 512GB',
    valueLow: 16,
    valueMid: 28,
    valueHigh: 42,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-020',
    category: 'ssd',
    name: '2.5" SATA SSD 1TB',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-021',
    category: 'ssd',
    name: 'M.2 NVMe SSD 256GB',
    valueLow: 12,
    valueMid: 22,
    valueHigh: 35,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-022',
    category: 'ssd',
    name: 'M.2 NVMe SSD 512GB',
    valueLow: 20,
    valueMid: 35,
    valueHigh: 52,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-023',
    category: 'ssd',
    name: 'M.2 NVMe SSD 1TB',
    valueLow: 38,
    valueMid: 65,
    valueHigh: 95,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-024',
    category: 'ssd',
    name: 'M.2 NVMe SSD 2TB',
    valueLow: 65,
    valueMid: 110,
    valueHigh: 160,
    demand: 'medium',
    notes: '',
  },

  // ─── HDDs ─────────────────────────────────────────────────────────────────
  {
    id: 'seed-025',
    category: 'hdd',
    name: '2.5" HDD 500GB',
    valueLow: 6,
    valueMid: 10,
    valueHigh: 16,
    demand: 'low',
    notes: 'Slow sellers — bundle or bulk',
  },
  {
    id: 'seed-026',
    category: 'hdd',
    name: '2.5" HDD 1TB',
    valueLow: 8,
    valueMid: 14,
    valueHigh: 22,
    demand: 'low',
    notes: '',
  },
  {
    id: 'seed-027',
    category: 'hdd',
    name: '3.5" HDD 1TB Desktop',
    valueLow: 12,
    valueMid: 20,
    valueHigh: 30,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-028',
    category: 'hdd',
    name: '3.5" HDD 2TB Desktop',
    valueLow: 18,
    valueMid: 32,
    valueHigh: 48,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-029',
    category: 'hdd',
    name: '3.5" HDD 4TB Desktop',
    valueLow: 35,
    valueMid: 58,
    valueHigh: 80,
    demand: 'medium',
    notes: '',
  },

  // ─── CPUs (Mobile) ────────────────────────────────────────────────────────
  {
    id: 'seed-030',
    category: 'cpu_mobile',
    name: 'Intel i5 7th Gen (mobile)',
    valueLow: 12,
    valueMid: 22,
    valueHigh: 35,
    demand: 'medium',
    notes: 'Kaby Lake — declining value',
  },
  {
    id: 'seed-031',
    category: 'cpu_mobile',
    name: 'Intel i5 8th Gen (mobile)',
    valueLow: 18,
    valueMid: 30,
    valueHigh: 45,
    demand: 'medium',
    notes: 'Whiskey Lake — still in demand',
  },
  {
    id: 'seed-032',
    category: 'cpu_mobile',
    name: 'Intel i5 10th Gen (mobile)',
    valueLow: 22,
    valueMid: 38,
    valueHigh: 55,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-033',
    category: 'cpu_mobile',
    name: 'Intel i5 12th Gen (mobile)',
    valueLow: 40,
    valueMid: 70,
    valueHigh: 100,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-034',
    category: 'cpu_mobile',
    name: 'Intel i7 8th Gen (mobile)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-035',
    category: 'cpu_mobile',
    name: 'Intel i7 10th Gen (mobile)',
    valueLow: 35,
    valueMid: 60,
    valueHigh: 88,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-036',
    category: 'cpu_mobile',
    name: 'Intel i7 12th Gen (mobile)',
    valueLow: 55,
    valueMid: 95,
    valueHigh: 135,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-037',
    category: 'cpu_mobile',
    name: 'AMD Ryzen 5 5500U (mobile)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 68,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-038',
    category: 'cpu_mobile',
    name: 'AMD Ryzen 7 5700U (mobile)',
    valueLow: 38,
    valueMid: 65,
    valueHigh: 92,
    demand: 'medium',
    notes: '',
  },

  // ─── CPUs (Desktop) ───────────────────────────────────────────────────────
  {
    id: 'seed-039',
    category: 'cpu_desktop',
    name: 'Intel i5 9th/10th Gen (desktop)',
    valueLow: 35,
    valueMid: 60,
    valueHigh: 90,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-040',
    category: 'cpu_desktop',
    name: 'Intel i5 12th/13th Gen (desktop)',
    valueLow: 85,
    valueMid: 135,
    valueHigh: 185,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-041',
    category: 'cpu_desktop',
    name: 'Intel i7 10th Gen (desktop)',
    valueLow: 55,
    valueMid: 90,
    valueHigh: 130,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-042',
    category: 'cpu_desktop',
    name: 'Intel i7 12th/13th Gen (desktop)',
    valueLow: 110,
    valueMid: 175,
    valueHigh: 240,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-043',
    category: 'cpu_desktop',
    name: 'AMD Ryzen 5 5600',
    valueLow: 70,
    valueMid: 110,
    valueHigh: 150,
    demand: 'high',
    notes: 'Very popular — fast seller',
  },
  {
    id: 'seed-044',
    category: 'cpu_desktop',
    name: 'AMD Ryzen 7 5800X',
    valueLow: 95,
    valueMid: 145,
    valueHigh: 200,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-045',
    category: 'cpu_desktop',
    name: 'AMD Ryzen 9 5900X',
    valueLow: 130,
    valueMid: 190,
    valueHigh: 260,
    demand: 'medium',
    notes: '',
  },

  // ─── GPUs ─────────────────────────────────────────────────────────────────
  {
    id: 'seed-046',
    category: 'gpu',
    name: 'NVIDIA GTX 1060 6GB',
    valueLow: 55,
    valueMid: 85,
    valueHigh: 115,
    demand: 'medium',
    notes: 'Still gets sold but slowing',
  },
  {
    id: 'seed-047',
    category: 'gpu',
    name: 'NVIDIA GTX 1070 8GB',
    valueLow: 70,
    valueMid: 105,
    valueHigh: 145,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-048',
    category: 'gpu',
    name: 'NVIDIA GTX 1070 Ti 8GB',
    valueLow: 80,
    valueMid: 120,
    valueHigh: 165,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-049',
    category: 'gpu',
    name: 'NVIDIA GTX 1080 8GB',
    valueLow: 90,
    valueMid: 135,
    valueHigh: 185,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-050',
    category: 'gpu',
    name: 'NVIDIA GTX 1080 Ti 11GB',
    valueLow: 130,
    valueMid: 195,
    valueHigh: 265,
    demand: 'high',
    notes: 'Strong demand — power users',
  },
  {
    id: 'seed-051',
    category: 'gpu',
    name: 'NVIDIA RTX 2060 6GB',
    valueLow: 100,
    valueMid: 155,
    valueHigh: 210,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-052',
    category: 'gpu',
    name: 'NVIDIA RTX 2060 Super',
    valueLow: 115,
    valueMid: 175,
    valueHigh: 235,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-053',
    category: 'gpu',
    name: 'NVIDIA RTX 2070 8GB',
    valueLow: 130,
    valueMid: 200,
    valueHigh: 270,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-054',
    category: 'gpu',
    name: 'NVIDIA RTX 2080 8GB',
    valueLow: 165,
    valueMid: 250,
    valueHigh: 340,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-055',
    category: 'gpu',
    name: 'NVIDIA RTX 3060 12GB',
    valueLow: 145,
    valueMid: 215,
    valueHigh: 285,
    demand: 'high',
    notes: 'Very popular',
  },
  {
    id: 'seed-056',
    category: 'gpu',
    name: 'NVIDIA RTX 3060 Ti',
    valueLow: 175,
    valueMid: 260,
    valueHigh: 345,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-057',
    category: 'gpu',
    name: 'NVIDIA RTX 3070 8GB',
    valueLow: 230,
    valueMid: 330,
    valueHigh: 430,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-058',
    category: 'gpu',
    name: 'NVIDIA RTX 3080 10GB',
    valueLow: 320,
    valueMid: 450,
    valueHigh: 580,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-059',
    category: 'gpu',
    name: 'NVIDIA RTX 3090 24GB',
    valueLow: 480,
    valueMid: 650,
    valueHigh: 820,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-060',
    category: 'gpu',
    name: 'NVIDIA RTX 4060 8GB',
    valueLow: 210,
    valueMid: 290,
    valueHigh: 370,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-061',
    category: 'gpu',
    name: 'NVIDIA RTX 4070 12GB',
    valueLow: 360,
    valueMid: 480,
    valueHigh: 600,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-062',
    category: 'gpu',
    name: 'AMD RX 580 8GB',
    valueLow: 45,
    valueMid: 70,
    valueHigh: 95,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-063',
    category: 'gpu',
    name: 'AMD RX 5700 XT',
    valueLow: 120,
    valueMid: 175,
    valueHigh: 230,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-064',
    category: 'gpu',
    name: 'AMD RX 6700 XT 12GB',
    valueLow: 180,
    valueMid: 255,
    valueHigh: 330,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-065',
    category: 'gpu',
    name: 'AMD RX 6800 XT',
    valueLow: 270,
    valueMid: 370,
    valueHigh: 470,
    demand: 'medium',
    notes: '',
  },

  // ─── BATTERIES ────────────────────────────────────────────────────────────
  {
    id: 'seed-066',
    category: 'battery',
    name: 'ThinkPad T/X/L Series Battery (61Wh)',
    valueLow: 22,
    valueMid: 35,
    valueHigh: 50,
    demand: 'high',
    notes: 'T470/T480/T490 compatible',
  },
  {
    id: 'seed-067',
    category: 'battery',
    name: 'Dell Latitude Battery (54Wh)',
    valueLow: 18,
    valueMid: 30,
    valueHigh: 44,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-068',
    category: 'battery',
    name: 'HP EliteBook Battery (56Wh)',
    valueLow: 18,
    valueMid: 30,
    valueHigh: 44,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-069',
    category: 'battery',
    name: 'MacBook Pro 13" Battery (58Wh)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-070',
    category: 'battery',
    name: 'MacBook Air Battery (50Wh)',
    valueLow: 22,
    valueMid: 38,
    valueHigh: 55,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-071',
    category: 'battery',
    name: 'Lenovo IdeaPad Battery',
    valueLow: 12,
    valueMid: 20,
    valueHigh: 30,
    demand: 'low',
    notes: 'Consumer lines — lower demand',
  },

  // ─── CHARGERS ─────────────────────────────────────────────────────────────
  {
    id: 'seed-072',
    category: 'charger',
    name: '65W USB-C Laptop Charger (ThinkPad/Dell)',
    valueLow: 10,
    valueMid: 18,
    valueHigh: 28,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-073',
    category: 'charger',
    name: '90W Barrel Charger (ThinkPad/Dell)',
    valueLow: 8,
    valueMid: 15,
    valueHigh: 24,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-074',
    category: 'charger',
    name: 'MacBook 61W USB-C Charger',
    valueLow: 22,
    valueMid: 35,
    valueHigh: 50,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-075',
    category: 'charger',
    name: 'MacBook 96W USB-C Charger',
    valueLow: 28,
    valueMid: 44,
    valueHigh: 62,
    demand: 'high',
    notes: '',
  },
  {
    id: 'seed-076',
    category: 'charger',
    name: '45W USB-C (budget laptops)',
    valueLow: 7,
    valueMid: 12,
    valueHigh: 18,
    demand: 'low',
    notes: '',
  },

  // ─── KEYBOARDS ────────────────────────────────────────────────────────────
  {
    id: 'seed-077',
    category: 'keyboard',
    name: 'ThinkPad Keyboard (US backlit)',
    valueLow: 18,
    valueMid: 28,
    valueHigh: 40,
    demand: 'high',
    notes: 'Easy to swap — consistent demand',
  },
  {
    id: 'seed-078',
    category: 'keyboard',
    name: 'ThinkPad Keyboard (US non-backlit)',
    valueLow: 12,
    valueMid: 20,
    valueHigh: 30,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-079',
    category: 'keyboard',
    name: 'Dell Latitude Keyboard (US)',
    valueLow: 10,
    valueMid: 18,
    valueHigh: 28,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-080',
    category: 'keyboard',
    name: 'HP EliteBook Keyboard (US)',
    valueLow: 10,
    valueMid: 18,
    valueHigh: 28,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-081',
    category: 'keyboard',
    name: 'MacBook Pro Keyboard/Topcase',
    valueLow: 45,
    valueMid: 80,
    valueHigh: 130,
    demand: 'medium',
    notes: 'Butterfly vs scissor matters',
  },

  // ─── MOTHERBOARDS ─────────────────────────────────────────────────────────
  {
    id: 'seed-082',
    category: 'motherboard',
    name: 'ThinkPad T480 Motherboard (i5-8250U)',
    valueLow: 38,
    valueMid: 65,
    valueHigh: 95,
    demand: 'medium',
    notes: 'Verify CPU/RAM spec',
  },
  {
    id: 'seed-083',
    category: 'motherboard',
    name: 'ThinkPad T470 Motherboard (i5-7200U)',
    valueLow: 28,
    valueMid: 48,
    valueHigh: 70,
    demand: 'low',
    notes: '',
  },
  {
    id: 'seed-084',
    category: 'motherboard',
    name: 'Dell Latitude 5480 Motherboard',
    valueLow: 32,
    valueMid: 55,
    valueHigh: 80,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-085',
    category: 'motherboard',
    name: 'Dell OptiPlex Motherboard (9th/10th Gen)',
    valueLow: 28,
    valueMid: 50,
    valueHigh: 75,
    demand: 'medium',
    notes: '',
  },
  {
    id: 'seed-086',
    category: 'motherboard',
    name: 'HP EliteBook 840 G5 Motherboard',
    valueLow: 35,
    valueMid: 60,
    valueHigh: 88,
    demand: 'medium',
    notes: '',
  },
];

export default COMPONENT_SEED;
